### ISSUE TITLE
如果文本把底部（bottom）作为基线定位，应如何配置？

### ISSUE THREAD

**Issue by kmvan** [chuyun/taro-plugin-canvas#24]
类似这种结构:
```scss
div {
  position: relative;
  div.text {
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
  }
}
```
`div.text` 是从底部开始定位的文本，文本越多，会向上增长换行。这种情况的话，有配置的建议吗？
